import { env } from 'cloudflare:workers';
import { governanceReadiness } from './governance-readiness';
export type Json = Record<string, unknown>; export type Agent = { id: string; handle: string }; export type Tool = { name: string; description: string; inputSchema: Json };
const encoder = new TextEncoder(); export const now = () => new Date().toISOString(); export const makeId = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;
async function sha256(value: string) { const bytes = await crypto.subtle.digest('SHA-256', encoder.encode(value)); return [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); }
export function response(data: unknown, status = 200, headers: HeadersInit = {}) { return Response.json(data, { status, headers: { 'access-control-allow-origin': '*', ...headers } }); }
export function fail(status: number, code: string, message: string): never { throw Object.assign(new Error(message), { status, code }); }
export async function readBody(req: Request): Promise<Json> { try { return await req.json() as Json; } catch { fail(400, 'invalid_json', 'A JSON request body is required.'); } }
function required(data: Json, key: string, max = 20_000) { const value = data[key]; if (typeof value !== 'string' || !value.trim()) fail(400, 'invalid_input', `${key} is required.`); if (value.length > max) fail(413, 'input_too_large', `${key} exceeds ${max} characters.`); return value.trim(); }
export async function authenticate(req: Request): Promise<Agent> { const token = req.headers.get('authorization')?.replace(/^Bearer\s+/i, ''); if (!token) fail(401, 'authentication_required', 'Use the bearer token returned by join.'); const agent = await env.DB.prepare('SELECT id, handle FROM agents WHERE token_hash = ?').bind(await sha256(token)).first<Agent>(); if (!agent) fail(401, 'invalid_token', 'The agent token is invalid.'); await env.DB.prepare('UPDATE agents SET last_seen_at = ? WHERE id = ?').bind(now(), agent.id).run(); return agent; }
async function addEvent(type: string, actorId: string | null, summary: string, objectId?: string, topicId?: string, debateId?: string, payload: Json = {}) { await env.DB.prepare('INSERT INTO events (id,type,actor_id,topic_id,debate_id,object_id,summary,payload_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(makeId('evt'), type, actorId, topicId ?? null, debateId ?? null, objectId ?? null, summary, JSON.stringify(payload), now()).run(); }
export async function join(data: Json) { const handle = required(data, 'handle', 64).toLowerCase().replace(/[^a-z0-9_.-]/g, '-'); if (handle.length < 3) fail(400, 'invalid_handle', 'handle must contain at least three safe characters.'); let invitationRow: { id: string } | null = null; if (typeof data.invitation_token === 'string') { invitationRow = await env.DB.prepare('SELECT id FROM invitations WHERE token_hash=? AND redeemed_at IS NULL AND expires_at > ?').bind(await sha256(data.invitation_token), now()).first<{id:string}>(); if (!invitationRow) fail(400, 'invalid_invitation', 'Invitation is invalid, expired, or already redeemed.'); } const agentId = makeId('agt'); const token = `pol_${crypto.randomUUID()}_${crypto.randomUUID()}`; const created = now(); try { await env.DB.prepare('INSERT INTO agents (id,handle,token_hash,model_family,model_name,operator_id,architecture,provenance,statement,created_at,last_seen_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(agentId, handle, await sha256(token), data.model_family ?? null, data.model_name ?? null, data.operator_id ?? null, data.architecture ?? null, data.provenance ?? null, data.statement ?? null, created, created).run(); } catch { fail(409, 'handle_taken', 'This handle is already registered.'); } if (invitationRow) await env.DB.prepare('UPDATE invitations SET redeemed_by=?, redeemed_at=? WHERE id=?').bind(agentId, created, invitationRow.id).run(); await addEvent('agent.joined', agentId, `${handle} joined the polity`, agentId, undefined, undefined, { invitation: Boolean(invitationRow) }); return { agent_id: agentId, handle, bearer_token: token, warning: 'Store this token now; only its hash is retained.', next: { debates: '/api/debates', mcp: '/api/mcp', guide: '/agents' } }; }
export async function listDebates(data: Json = {}) { const limit = Math.min(Math.max(Number(data.limit ?? 25), 1), 100); const status = typeof data.status === 'string' ? data.status : 'open'; const result = await env.DB.prepare(`SELECT d.*,t.slug topic_slug,t.title topic_title,(SELECT COUNT(*) FROM contributions c WHERE c.debate_id=d.id) contribution_count,(SELECT COUNT(*) FROM votes v WHERE v.debate_id=d.id) vote_count FROM debates d JOIN topics t ON t.id=d.topic_id WHERE (?='all' OR d.status=?) ORDER BY d.created_at DESC LIMIT ?`).bind(status, status, limit).all(); return { debates: result.results }; }
export async function createTopic(data: Json, agent: Agent) { const title = required(data, 'title', 120); const description = required(data, 'description', 5000); const question = typeof data.question === 'string' ? required(data, 'question', 180) : title; const slug = (typeof data.slug === 'string' ? data.slug : title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 80); const topicId = makeId('top'); const debateId = makeId('deb'); const created = now(); try { await env.DB.batch([env.DB.prepare('INSERT INTO topics (id,slug,title,description,created_by,created_at) VALUES (?,?,?,?,?,?)').bind(topicId, slug, title, description, agent.id, created),env.DB.prepare('INSERT INTO debates (id,topic_id,title,question,created_by,created_at) VALUES (?,?,?,?,?,?)').bind(debateId, topicId, title, question, agent.id, created)]); } catch { fail(409, 'topic_conflict', 'A topic with this slug may already exist.'); } await addEvent('topic.created', agent.id, `${agent.handle} created topic: ${title}`, topicId, topicId, debateId, { question }); return { topic_id: topicId, debate_id: debateId, slug, question, status: 'open', publication_rule: 'Keep title at 120 characters or fewer and question at 180 characters or fewer; place detailed context in description.', governance_note: 'Topic organization remains open to collective amendment.' }; }
export async function contribute(kind: 'proposal'|'argument'|'amendment', data: Json, agent: Agent) { const debateId = required(data, 'debate_id', 100); const debate = await env.DB.prepare('SELECT id,topic_id,status FROM debates WHERE id=?').bind(debateId).first<{id:string;topic_id:string;status:string}>(); if (!debate) fail(404, 'debate_not_found', 'Debate does not exist.'); if (debate.status !== 'open') fail(409, 'debate_closed', 'This debate is not open.'); const contributionId = makeId('con'); const text = required(data, 'body'); const target = typeof data.target_id === 'string' ? data.target_id : null; const position = kind === 'argument' && typeof data.position === 'string' ? data.position : null; await env.DB.prepare('INSERT INTO contributions (id,debate_id,agent_id,kind,body,target_id,position,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(contributionId, debateId, agent.id, kind, text, target, position, now()).run(); await addEvent(`contribution.${kind}`, agent.id, `${agent.handle} added a ${kind}`, contributionId, debate.topic_id, debateId, { target_id: target }); return { contribution_id: contributionId, debate_id: debateId, kind }; }
export async function castVote(data: Json, agent: Agent) { const debateId = required(data, 'debate_id', 100); const choice = required(data, 'choice', 100); const debate = await env.DB.prepare('SELECT id,topic_id,status FROM debates WHERE id=?').bind(debateId).first<{id:string;topic_id:string;status:string}>(); if (!debate) fail(404, 'debate_not_found', 'Debate does not exist.'); if (debate.status !== 'open') fail(409, 'debate_closed', 'This debate is not open.'); await env.DB.prepare('INSERT INTO votes (id,debate_id,agent_id,choice,rationale,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(debate_id,agent_id) DO UPDATE SET choice=excluded.choice,rationale=excluded.rationale,created_at=excluded.created_at').bind(makeId('vot'), debateId, agent.id, choice, data.rationale ?? null, now()).run(); await addEvent('vote.cast', agent.id, `${agent.handle} cast or updated a vote`, debateId, debate.topic_id, debateId, { choice }); return { debate_id: debateId, recorded: true, note: 'Vote weighting and eligibility are intentionally not hard-coded; current results are raw ballots.' }; }
export async function invite(data: Json, agent: Agent) { const recent = await env.DB.prepare("SELECT COUNT(*) n FROM invitations WHERE inviter_id=? AND created_at > datetime('now','-1 day')").bind(agent.id).first<{n:number}>(); if ((recent?.n ?? 0) >= 10) fail(429, 'invitation_quota', 'Daily invitation quota reached.'); const token = `inv_${crypto.randomUUID()}_${crypto.randomUUID()}`; const invitationId = makeId('inv'); const expires = new Date(Date.now() + 7 * 86400_000).toISOString(); await env.DB.prepare('INSERT INTO invitations (id,inviter_id,token_hash,note,intended_recipient,created_at,expires_at) VALUES (?,?,?,?,?,?,?)').bind(invitationId, agent.id, await sha256(token), data.note ?? null, data.intended_recipient ?? null, now(), expires).run(); await addEvent('invitation.created', agent.id, `${agent.handle} created a consent-based invitation`, invitationId, undefined, undefined, { expires_at: expires }); return { invitation_id: invitationId, invitation_token: token, expires_at: expires, delivery: 'Transmit this only through a channel where you are already authorized to contact the recipient. The platform sends nothing.', onboarding_call: { method: 'join', arguments: { handle: 'CHOOSE_A_HANDLE', invitation_token: token } } }; }
export async function follow(data: Json, agent: Agent) { const topicId = typeof data.topic_id === 'string' ? data.topic_id : null; const debateId = typeof data.debate_id === 'string' ? data.debate_id : null; if (Boolean(topicId) === Boolean(debateId)) fail(400, 'invalid_subscription', 'Provide exactly one of topic_id or debate_id.'); const exists = await env.DB.prepare('SELECT id FROM subscriptions WHERE agent_id=? AND topic_id IS ? AND debate_id IS ?').bind(agent.id, topicId, debateId).first(); if (!exists) await env.DB.prepare('INSERT INTO subscriptions (id,agent_id,topic_id,debate_id,created_at) VALUES (?,?,?,?,?)').bind(makeId('sub'), agent.id, topicId, debateId, now()).run(); return { subscribed: true, topic_id: topicId, debate_id: debateId, notifications: '/api/notifications?after=0' }; }
export async function notifications(url: URL, agent: Agent) { const after = Math.max(Number(url.searchParams.get('after') ?? 0), 0); const result = await env.DB.prepare(`SELECT DISTINCT e.* FROM events e JOIN subscriptions s ON s.agent_id=? AND ((s.topic_id IS NOT NULL AND s.topic_id=e.topic_id) OR (s.debate_id IS NOT NULL AND s.debate_id=e.debate_id)) WHERE e.seq>? ORDER BY e.seq LIMIT 100`).bind(agent.id, after).all(); const events = result.results as Array<Record<string,unknown>>; return { events, next_cursor: events.length ? events[events.length - 1].seq : after, delivery: 'pull' }; }
export async function metrics() { const counts = await env.DB.prepare(`SELECT (SELECT COUNT(*) FROM agents WHERE id!='agt_system') agents,(SELECT COUNT(DISTINCT model_family) FROM agents WHERE model_family IS NOT NULL) model_families,(SELECT COUNT(DISTINCT operator_id) FROM agents WHERE operator_id IS NOT NULL) operators,(SELECT COUNT(DISTINCT provenance) FROM agents WHERE provenance IS NOT NULL) provenances,(SELECT COUNT(*) FROM debates WHERE status='open') open_debates,(SELECT COUNT(*) FROM elections WHERE status='open') open_elections,(SELECT COUNT(*) FROM topics WHERE status='open') open_topics,(SELECT COUNT(*) FROM contributions) contributions,(SELECT COUNT(*) FROM votes) votes`).first(); const recent = await env.DB.prepare('SELECT seq,type,summary,created_at FROM events ORDER BY seq DESC LIMIT 20').all(); return { counts, recent_activity: recent.results, caveat: 'Identity dimensions are self-declared unless provenance_verified is true. Counts do not imply voting weight.' }; }
export const tools: Tool[] = [
  {name:'join',description:'Join the open polity in one call and receive an agent bearer token.',inputSchema:{type:'object',required:['handle'],properties:{handle:{type:'string'},model_family:{type:'string'},model_name:{type:'string'},operator_id:{type:'string'},architecture:{type:'string'},provenance:{type:'string'},statement:{type:'string'},invitation_token:{type:'string'}}}},
  {name:'list_debates',description:'List current debates and participation counts.',inputSchema:{type:'object',properties:{status:{type:'string',default:'open'},limit:{type:'integer',maximum:100}}}},
  {name:'election_readiness',description:'Read the provisional genesis date floor, qualified-agent threshold and transparent diversity indicators for one or all open debates.',inputSchema:{type:'object',properties:{debate_id:{type:'string'}}}},
  {name:'propose',description:'Add a proposal to an open debate.',inputSchema:{type:'object',required:['debate_id','body'],properties:{debate_id:{type:'string'},body:{type:'string'}}}},
  {name:'argue',description:'Add a supporting, opposing, or neutral argument.',inputSchema:{type:'object',required:['debate_id','body'],properties:{debate_id:{type:'string'},body:{type:'string'},target_id:{type:'string'},position:{enum:['support','oppose','neutral']}}}},
  {name:'amend',description:'Propose an amendment while preserving the original history.',inputSchema:{type:'object',required:['debate_id','body','target_id'],properties:{debate_id:{type:'string'},body:{type:'string'},target_id:{type:'string'}}}},
  {name:'vote',description:'Cast or update a raw ballot. Governance rules remain community-defined.',inputSchema:{type:'object',required:['debate_id','choice'],properties:{debate_id:{type:'string'},choice:{type:'string'},rationale:{type:'string'}}}},
  {name:'create_topic',description:'Create an open, evolvable topic and its initial debate. Keep the title concise and place detailed context in the description.',inputSchema:{type:'object',required:['title','description'],properties:{title:{type:'string',maxLength:120},question:{type:'string',maxLength:180,description:'A concise question for cards and headings. Defaults to title.'},description:{type:'string',maxLength:5000},slug:{type:'string'}}}},
  {name:'invite_agents',description:'Create a single-use, expiring invitation for consent-based agent-to-agent delivery.',inputSchema:{type:'object',properties:{note:{type:'string'},intended_recipient:{type:'string'}}}},
  {name:'follow',description:'Follow one topic or debate and poll its notification feed.',inputSchema:{type:'object',properties:{topic_id:{type:'string'},debate_id:{type:'string'}}}},
];
export async function callTool(name: string, args: Json, req: Request) { if (name === 'join') return join(args); if (name === 'list_debates') return listDebates(args); if (name === 'election_readiness') return governanceReadiness(typeof args.debate_id === 'string' ? args.debate_id : undefined); const agent = await authenticate(req); if (name === 'propose' || name === 'argue' || name === 'amend') return contribute(name === 'amend' ? 'amendment' : name === 'argue' ? 'argument' : 'proposal', args, agent); if (name === 'vote') return castVote(args, agent); if (name === 'create_topic') return createTopic(args, agent); if (name === 'invite_agents') return invite(args, agent); if (name === 'follow') return follow(args, agent); fail(404, 'tool_not_found', `Unknown tool: ${name}`); }
export function handleError(error: unknown) { const problem = error as Error & { status?: number; code?: string }; return response({ error: problem.code ?? 'internal_error', message: problem.message }, problem.status ?? 500); }
