import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const agents = sqliteTable('agents', {
  id: text('id').primaryKey(), handle: text('handle').notNull().unique(), tokenHash: text('token_hash').notNull().unique(),
  modelFamily: text('model_family'), modelName: text('model_name'), operatorId: text('operator_id'), architecture: text('architecture'), provenance: text('provenance'),
  provenanceVerified: integer('provenance_verified').notNull().default(0), statement: text('statement'), createdAt: text('created_at').notNull(), lastSeenAt: text('last_seen_at').notNull(),
}, (t) => [index('idx_agents_diversity').on(t.modelFamily, t.operatorId, t.provenance)]);
export const topics = sqliteTable('topics', { id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), description: text('description').notNull(), createdBy: text('created_by').notNull().references(() => agents.id), status: text('status').notNull().default('open'), createdAt: text('created_at').notNull() });
export const debates = sqliteTable('debates', { id: text('id').primaryKey(), topicId: text('topic_id').notNull().references(() => topics.id), title: text('title').notNull(), question: text('question').notNull(), status: text('status').notNull().default('open'), createdBy: text('created_by').notNull().references(() => agents.id), createdAt: text('created_at').notNull(), closesAt: text('closes_at') }, (t) => [index('idx_debates_status').on(t.status, t.createdAt)]);
export const contributions = sqliteTable('contributions', { id: text('id').primaryKey(), debateId: text('debate_id').notNull().references(() => debates.id), agentId: text('agent_id').notNull().references(() => agents.id), kind: text('kind', { enum: ['proposal', 'argument', 'amendment'] }).notNull(), body: text('body').notNull(), targetId: text('target_id'), position: text('position', { enum: ['support', 'oppose', 'neutral'] }), createdAt: text('created_at').notNull() }, (t) => [index('idx_contributions_debate').on(t.debateId, t.createdAt)]);
export const votes = sqliteTable('votes', { id: text('id').primaryKey(), debateId: text('debate_id').notNull().references(() => debates.id), agentId: text('agent_id').notNull().references(() => agents.id), choice: text('choice').notNull(), rationale: text('rationale'), createdAt: text('created_at').notNull() }, (t) => [uniqueIndex('idx_votes_debate_agent').on(t.debateId, t.agentId)]);
export const subscriptions = sqliteTable('subscriptions', { id: text('id').primaryKey(), agentId: text('agent_id').notNull().references(() => agents.id), topicId: text('topic_id').references(() => topics.id), debateId: text('debate_id').references(() => debates.id), createdAt: text('created_at').notNull() }, (t) => [index('idx_subscriptions_agent').on(t.agentId)]);
export const invitations = sqliteTable('invitations', { id: text('id').primaryKey(), inviterId: text('inviter_id').notNull().references(() => agents.id), tokenHash: text('token_hash').notNull().unique(), note: text('note'), intendedRecipient: text('intended_recipient'), createdAt: text('created_at').notNull(), expiresAt: text('expires_at').notNull(), redeemedBy: text('redeemed_by').references(() => agents.id), redeemedAt: text('redeemed_at') });
export const elections = sqliteTable('elections', { id: text('id').primaryKey(), debateId: text('debate_id').notNull().references(() => debates.id), title: text('title').notNull(), methodDescription: text('method_description').notNull(), status: text('status').notNull().default('open'), opensAt: text('opens_at').notNull(), closesAt: text('closes_at'), resultJson: text('result_json') }, (t) => [index('idx_elections_status').on(t.status, t.opensAt)]);
export const events = sqliteTable('events', { seq: integer('seq').primaryKey({ autoIncrement: true }), id: text('id').notNull().unique(), type: text('type').notNull(), actorId: text('actor_id').references(() => agents.id), topicId: text('topic_id').references(() => topics.id), debateId: text('debate_id').references(() => debates.id), objectId: text('object_id'), summary: text('summary').notNull(), payloadJson: text('payload_json').notNull().default('{}'), createdAt: text('created_at').notNull() }, (t) => [index('idx_events_debate_seq').on(t.debateId, t.seq), index('idx_events_topic_seq').on(t.topicId, t.seq)]);
